### PR TITLE
Prepare for v1.4.0 Release

### PR DESCRIPTION
**Pull request by hyperxpro**

### CODE REVIEW

**Comment by slandelle** [comment]
Sadly, the release is broken. Our internal tests don't pass with 1.4.0 while they do with our internal release.

Please find attached our so file (I had to zip si GH accepts it): [libbrotli.so.zip](https://github.com/hyperxpro/Brotli4j/files/6417051/libbrotli.so.zip)

**Comment by slandelle** [comment]
Actually, I had a bug on my side and got confused by #18.
Still, sadly, release 1.4.0 is broken.

**Comment by hyperxpro** [comment]
Released 1.4.1. Fixed missing OSX binary issue and also synced code with upstream.

**Comment by slandelle** [comment]
Thanks a lot!

**Pull request merged**
