### PR TITLE
Match Netty scheme for native modules naming, close #6

### LINKED ISSUE #6: Publish native modules with name that follows Netty's naming scheme
Hi @hyperxpro !

I'd like to work on PR for Netty to bring Brotli decoder support.

However, the current naming scheme makes it very cumbersome (I would have to play with profiles to map the netty scheme to brotly4j's current one.

Would it be possible to change it?

* `native-macos_x86-64` => `native-osx-x86_64`
* `native-linux_x86-64` => `native-linux-x86_64`
* `native-windows_x86-64` => `native-windows-x86_64`

Basically:
* `macos` => `osx`
* `x86-64` => `x86_64` (underscore)

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

Netty uses a different naming scheme than the one currently used here, making it complicated to integrate.

Modifications:

* linux-x86_64
* osx-x86_64
* windows-x86_64

Result:

Easier to integrate with Netty

### CODE REVIEW

**Comment by hyperxpro** [comment]
Should we use `classifier` instead of automatically pulling the right native?

**Comment by slandelle** [comment]
Your call. I'm just not fond of classifiers because classifier support is currently broken in [sbt](https://github.com/sbt/sbt/issues/5325) :(

**Comment by hyperxpro** [comment]
Alright, lemme test this with CI.

**Comment by hyperxpro** [comment]
https://github.com/hyperxpro/Brotli4j/actions/runs/503396295

Can you just test macOS locally?

**Comment by hyperxpro** [comment]
I will do some tweaks to this. Thanks a lot. :)

**Comment by slandelle** [comment]
> Can you just test macOS locally?

Yep, I installed locally and it works fine.

**Pull request merged**
