### PR TITLE
Jpms fixup

### PR DESCRIPTION
**Pull request by ichttt**
As the title says, the pull request you already merged doesn't cover all issues.

This PR changes the discovery of the native jar to a servicer loader based approach. This means that application using brotli4j just has to depend on the brotli4j main module in their module-info, and brotli4j will implicitly depend on the other modules due to their service implementation. In non-JPMS environments, this doesn't change a thing, as the service loader will be unable to find any provider and fall back to the Loader class.
I tested this on a Windows 11 machine with J17 with JPMS enabled and with J11 with a old-school non JPMS application.
I also tested that linux J17 JPMS works as expected, both in production and dev environments.

Two notes:
First, I had to move the tests to a separate module, as it would otherwise cause a cyclic dependency. And second, I think you might have to upgrade java version of the CI to 11/17, as the maven plugin requires java9+ to work. But that should not be a problem as the resulting jars should still work with java 8 due to the source/target compat setting.

### CODE REVIEW

**Comment by hyperxpro** [comment]
Can you rebase so CI can be triggered?

**Comment by ichttt** [comment]
I've done that, but it seems like CI is still not running (at least I don't see any check on the commits/the PR)

**Comment by hyperxpro** [comment]
Fixed the Workflow. :( Please rebase for the last time.

**Comment by hyperxpro** [comment]
PTAL at build failure.

**Comment by ichttt** [comment]
After some further research into the maven moditect plugin, I found a way how to build on J8 while still including the J9 module-info. Validated using J11 non-JPMS application and J17 JPMS application on linux. Should be good to go now (finally)

**Comment by hyperxpro** [comment]
Can you rebase for the last time? I've plenty of new CIs to test the code more thoroughly.

**Comment by hyperxpro** [comment]
After that, I'll merge and cut the release.

**Comment by ichttt** [comment]
Should this PR still target the 1.9.0 branch? Because the new CI tests are not yet on the 1.9.0 branch, so I've cherry picked them for now. Once you merge these commits into I can properly rebase on the latest version

**Comment by hyperxpro** [comment]
That's it. I will take care of rest. Thanks a lot! :)

**Pull request merged**
