### PR TITLE
Add support for setting a mode

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Comment by hyperxpro** [comment]
@slandelle Any comments?

**Comment by hyperxpro** [comment]
@martin-g IMHO, We should contribute this upstream also.

**Review by hyperxpro — CHANGES_REQUESTED** [review]
Add test cases also, please.

**Comment by slandelle** [comment]
@slandelle No particular comment, except as I agree this should be contributed upstream so this project doesn't break someday before an upstream breaking change.

**Comment by martin-g** [comment]
> @martin-g IMHO, We should contribute this upstream also.

The C code is already at https://github.com/hyperxpro/Brotli4j/blob/8e20c8b4acdd365684686ef9e9731200001a10a4/brotli/include/brotli/encode.h#L45-L57

**Comment by hyperxpro** [comment]
How about Java code upstream contribution?

**Comment by slandelle** [comment]
@martin-g @hyperxpro is referring to the enum and the change to the JNI layer.

**Comment by martin-g** [comment]
Sorry, I am not aware how much of this project is a copy of google/brotli.
I thought that submodule `brotli` is the copy from Google and `brotli4j` is created by @hyperxpro 
Could you please clarify which files need to be updated upstream ?

**Comment by martin-g** [comment]
https://github.com/google/brotli/pull/887

**Comment by martin-g** [comment]
> Add test cases also, please.

Done! 
FONT mode gives different outcome for the used input. I was not able to find an input that produces different results for GENERIC and TEXT.

**Pull request merged**
