### PR TITLE
Add Tests of BrotliDecoderChannel

### PR DESCRIPTION
**Pull request by joakime**
Motivation:

Noticed there were no tests for BrotliDecoderChannel, so here are a few for you to add.

Modification:

Created test cases for BrotliDecoderChannel.

Result:

See test cases

### CODE REVIEW

**Review by hyperxpro — APPROVED** [review]

**Comment by hyperxpro** [comment]
Let me know if you want me to cut a release.

**Comment by joakime** [comment]
> Let me know if you want me to cut a release.

Still working on the basics of integration on my side.
If you want to cut a release in the next month or two for your own reasons, don't let me stop you.

There's no rush for a release of brotli4j from me (yet).

**Comment by hyperxpro** [comment]
I don't have any release timeline but I'd help in every possible way to help in your integration in Jetty. :)

Btw, is the PR up?

**Comment by hyperxpro** [comment]
Thanks a lot!

**Pull request merged**
