### PR TITLE
fix CMakefile

### PR DESCRIPTION
**Pull request by ericmolle**
fix for build on centos6
 - cmake directive
 - change compiler to gcc5 to match the right ABI

### CODE REVIEW

**Comment by slandelle** [comment]
@hyperxpro This one's good to go! Looking forward to the release :)

**Comment by hyperxpro** [comment]
@slandelle Released 1.4.2. :)

**Comment by slandelle** [comment]
Awesome! I've just updated the PR for Netty, let's cross fingers.

**Comment by hyperxpro** [comment]
Perfect. Let's hope for the best. :D

**Comment by hyperxpro** [comment]
@slandelle I have got a question about AHC. Is AHC capable of Millions of requests per second?

**Comment by slandelle** [comment]
@hyperxpro Depends on context: number of connections, keep-alive, https or clear, compression, payload size... You'd need lots of cores for 2M rps.

Note: I stepped down as AHC maintainer. Gatling has its own internal HTTP client.

**Comment by hyperxpro** [comment]
Thanks for the info. :D

**Comment by hyperxpro** [comment]
@slandelle I've something to show about the Gatling website. Can't DM you on Twitter. Can you hit me back? https://twitter.com/HyperXPro

**Comment by hyperxpro** [comment]
Dropped you an email.

**Pull request merged**
