### PR TITLE
Support for LoongArch64

### PR DESCRIPTION
**Pull request by Panxuefeng-loongson**

### CODE REVIEW

**Comment by hyperxpro** [comment]
Please ping me when it's ready for review. :)

**Comment by Panxuefeng-loongson** [comment]
RFR, thanks @hyperxpro

**Comment by hyperxpro** [comment]
You need to add a native module of `LoongArch64` for the project to build. Also, update the CI workflow file for running tests.

**Comment by Panxuefeng-loongson** [comment]
> You need to add a native module of `LoongArch64` for the project to build. Also, update the CI workflow file for running tests.
I don't know if you have a loongarch machine, If there is no machine, does the CI workflow file not need to be modified?

**Comment by hyperxpro** [comment]
Use QEMU in Docker. :)

**Comment by Panxuefeng-loongson** [comment]
> Use QEMU in Docker. :)

I'm not quite sure how to modify CI workflow, is it possible to merge this patch into the repo? You then make changes to the CI workflow file？

**Comment by hyperxpro** [comment]
Unfortunately, I can't merge until I have CI passing on this architecture.

**Comment by Panxuefeng-loongson** [comment]
I am not familiar with how to modify CI workflow, I may need your help. Thanks

**Comment by hyperxpro** [comment]
Alright, I will try this.

**Comment by Panxuefeng-loongson** [comment]
> Alright, I will try this.

Thanks

**Pull request closed without merging**
